services:
  frontend:
    image: node:23
    container_name: react-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run build && npx serve -s dist"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    networks:
      - my_custom_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: express-backend
    working_dir: /app
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      - my_custom_network

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_custom_network

volumes:
  postgres_data:

networks:
  my_custom_network:
    driver: bridge
