services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "4173:4173"
    depends_on:
      - backend
    networks:
      - my_custom_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: express-backend
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - my_custom_network

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    hostname: postgres-db
    networks:
      - my_custom_network

volumes:
  postgres_data:

networks:
  my_custom_network:
